//! Auto-generated thin wrapper for the Abliteration.ai provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct AbliterationAiProvider;
impl AbliterationAiProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "abliteration_ai",
            "Abliteration.ai",
            "Abliteration.ai — OpenAI-compatible endpoint.",
            "https://abliteration.ai",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://api.abliteration.ai/v1"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
