//! Auto-generated thin wrapper for the Alibaba (China) provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct AlibabaCnProvider;
impl AlibabaCnProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "alibaba_cn",
            "Alibaba (China)",
            "Alibaba (China) — OpenAI-compatible endpoint.",
            "https://www.alibabacloud.com/help/en/model-studio/",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://dashscope.aliyuncs.com/compatible-mode/v1"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
