//! Auto-generated thin wrapper for the avian provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct AvianProvider;
impl AvianProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "avian",
            "avian",
            "avian — OpenAI-compatible endpoint.",
            "https://avian.io/",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://api.avian.io/v1/"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
