//! Auto-generated thin wrapper for the IO.NET provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct IoNetProvider;
impl IoNetProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "io_net",
            "IO.NET",
            "IO.NET — OpenAI-compatible endpoint.",
            "https://io.net",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://api.intelligence.io.solutions/api/v1"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
