//! Auto-generated thin wrapper for the Jiekou.AI provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct JiekouProvider;
impl JiekouProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "jiekou",
            "Jiekou.AI",
            "Jiekou.AI — OpenAI-compatible endpoint.",
            "https://jiekou.ai",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://api.jiekou.ai/openai"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
