//! Auto-generated thin wrapper for the Kenari provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct KenariProvider;
impl KenariProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "kenari",
            "Kenari",
            "Kenari — OpenAI-compatible endpoint.",
            "https://kenari.id",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://kenari.id/v1"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
