//! Auto-generated thin wrapper for the Moark provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct MoarkProvider;
impl MoarkProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "moark",
            "Moark",
            "Moark — OpenAI-compatible endpoint.",
            "https://moark.com",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://moark.com/v1"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
