//! Auto-generated thin wrapper for the NEAR AI Cloud provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct NearaiProvider;
impl NearaiProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "nearai",
            "NEAR AI Cloud",
            "NEAR AI Cloud — OpenAI-compatible endpoint.",
            "https://near.ai",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://cloud-api.near.ai/v1"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
