//! Auto-generated thin wrapper for the Ofox provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct OfoxProvider;
impl OfoxProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "ofox",
            "Ofox",
            "Ofox — OpenAI-compatible endpoint.",
            "https://ofox.ai",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://api.ofox.ai/v1"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
