//! Auto-generated thin wrapper for the OVHcloud AI Endpoints provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct OvhcloudProvider;
impl OvhcloudProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "ovhcloud",
            "OVHcloud AI Endpoints",
            "OVHcloud AI Endpoints — OpenAI-compatible endpoint.",
            "https://www.ovhcloud.com/en/public-cloud/ai-endpoints/",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://oai.endpoints.kepler.ai.cloud.ovh.net/v1"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
