//! Auto-generated thin wrapper for the routing.run provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct RoutingRunProvider;
impl RoutingRunProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "routing_run",
            "routing.run",
            "routing.run — OpenAI-compatible endpoint.",
            "https://routing.run",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://ai.routing.sh/v1"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
