//! Auto-generated thin wrapper for the Vercel AI Gateway provider.
//!
//! Generated by `scripts/gen_providers.py` from the v0.4 AI model catalog.
//! Delegates to [`crate::ai::providers::openai_compat`] — every provider in
//! this group exposes an OpenAI-compatible `/v1/chat/completions` endpoint.

use std::sync::Arc;

use crate::ai::provider::{Provider, ProviderCategory};
use crate::ai::providers::openai_compat::{descriptor, make};

pub struct VercelProvider;
impl VercelProvider {
    pub fn new() -> Arc<dyn Provider> {
        make(descriptor(
            "vercel",
            "Vercel AI Gateway",
            "Vercel AI Gateway — OpenAI-compatible endpoint.",
            "https://vercel.com/ai-gateway",
            ProviderCategory::CloudOther,
            true,
            false,
            Some("https://ai-gateway.vercel.sh/v1"),
            "gpt-3.5-turbo",
            &["gpt-3.5-turbo"],
            true,
        ))
    }
}
